# Virtual DOM based JavaScript framework for building dynamic websites.
# Copyright (C) 2022 Amin NAIRI
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
version: "3"

services:
  node:
    image: node:17.0.0-alpine
    user: node
    entrypoint: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    volumes:
      - .:/home/node

  npm:
    extends: node
    entrypoint: npm

  npx:
    extends: node
    entrypoint: npx
