name: Publish

on:
  push:
    branches:
      - production

jobs:
  publish:
    name: Publish the package on the GitHub registry
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: echo -e "@aminnairi:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
      - name: Dependencies
        run: docker-compose run --rm --user root -T npm install
      - name: Build
        run: docker-compose run --rm --user root -T npm run build
      - name: Publish
        run: docker-compose run --rm --user root -T npm publish
